---
- name: "configure_ssh | ~{{ item.key }}/.ssh/"
  file:
    path: "~{{ item.key }}/.ssh/"
    owner: "{{ item.key }}"
    group: "{{ item.value.group | default(item.key) }}"
    mode: 0700
    state: directory
  when: "'authorized_keys' in item.value"

- name: "configure_ssh | ~{{ item.key }}/.ssh/authorized_keys"
  template:
    dest: "~{{ item.key }}/.ssh/authorized_keys"
    src: users/authorized_keys.j2
    owner: "{{ item.key }}"
    group: "{{ item.value.group | default(item.key) }}"
    mode: 0600
  when: "'authorized_keys' in item.value"

- name: "configure_ssh | ~{{ item.key }}/.ssh/config"
  template:
    src: "{{ user_ssh_config_template }}"
    dest: "~{{ item.key }}/.ssh/config"
    owner: "{{ item.key }}"
    group: "{{ item.value.group | default(item.key) }}"
    mode: 0600
  when: "'ssh_config' in item.value"