---
- name: "configure_vim | ~{{ item.key }}/.vimrc"   # noqa name
  ansible.builtin.template:
    src: "{{ users_vimrc_template }}"
    dest: "~{{ item.key }}/.vimrc"
    owner: "{{ item.key }}"
    group: "{{ item.value.group | default(item.key) }}"
    mode: 0600
  when: (item.value.vimrc is defined and item.value.vimrc|length>0) or users_default_vimrc|length>0
