---
- name: "configure_profile | {{ item.key }}/.profile"
  template:
    src: "{{ user_profile_template }}"
    dest: "~{{ item.key }}/.profile"
    owner: "root"
    group: "root"
    mode: 0644
  when: "'profile' in item.value"