---
- name: "configure_ssh | ~{{ item.key }}/.ssh/"
  file:
    path: "~{{ item.key }}/.ssh/"
    owner: "{{ item.key }}"
    group: "{{ item.value.group | default(item.key) }}"
    mode: 0700
    state: directory
  when: item.value.authorized_keys is defined or
        item.value.ssh_config is defined or
        item.value.ssh_keys is defined

- name: "configure_ssh | ~{{ item.key }}/.ssh/authorized_keys"
  template:
    dest: "~{{ item.key }}/.ssh/authorized_keys"
    src: "{{ users_authorized_keys_template }}"
    owner: "{{ item.key }}"
    group: "{{ item.value.group | default(item.key) }}"
    mode: 0600
  when: item.value.authorized_keys is defined

- name: "configure_ssh | ~{{ item.key }}/.ssh/config"
  template:
    src: "{{ users_ssh_config_template }}"
    dest: "~{{ item.key }}/.ssh/config"
    owner: "{{ item.key }}"
    group: "{{ item.value.group | default(item.key) }}"
    mode: 0600
  when: item.value.ssh_config is defined

- name: "configure_ssh | adding a public key to ssh folder for ~{{ item.key }}"
  copy:
    content: "{{ ssh_keys.value.public }}"
    dest: "~{{ item.key }}/.ssh/{{ ssh_keys.key }}.pub"
    owner: "{{ item.key }}"
    group: "{{ item.value.group | default(item.key) }}"
    mode: 0600
  loop: "{{ item.value.ssh_keys | default({}) | dict2items }}"
  loop_control:
    loop_var: ssh_keys
  when: ssh_keys.value.public is defined

- name: "configure_ssh | adding a private key to ssh folder for ~{{ item.key }}"
  copy:
    content: "{{ ssh_keys.value.private }}"
    dest: "~{{ item.key }}/.ssh/{{ ssh_keys.key }}"
    owner: "{{ item.key }}"
    group: "{{ item.value.group | default(item.key) }}"
    mode: 0600
  loop: "{{ item.value.ssh_keys | default({}) | dict2items }}"
  loop_control:
    loop_var: ssh_keys
  when: ssh_keys.value.private is defined
