- name: "configure_bash | {{ item.value.home }}/.bashrc"
  template:
    src: "{{ user_bashrc_template }}"
    dest: "~{{ item.key }}/.bashrc"
    owner: "{{ item.key }}"
    group: "{{ item.value.group | default(item.key) }}"
    mode: 0600
  when: "'bashrc' in item.value"

- name: "configure_bash | ensure {{ item.value.home }}/.bash_history is immutable"
  file:
    path: "~{{ item.key }}/.bash_history"
    attr: a
    state: touch
    owner: "{{ item.key }}"
    group: "{{ item.value.group | default(item.key) }}"
  changed_when: false
