---
- name: "create_groups | ensure {{ item.value.home }}/.bash_history exists"
  stat:
    path: "{{ item.value.home }}/.bash_history"
  register: history

- name: "create_groups | ensure {{ item.value.home }}/.bash_history is NOT immutable"
  file:
    path: "{{ item.value.home }}/.bash_history"
    attr: -a
  changed_when: false
  when: history.stat.exists

- name: "create_groups | create group {{ item.value.group }}"
  group:
    name: "{{ item.value.group }}"
    gid: "{{ item.value.gid | default(omit) }}"
  when: "'group' in item.value"
