---
- name: "hardening | ensure ~{{ item.key }}/.bash_history exists"
  stat:
    path: "~{{ item.key }}/.bash_history"
  register: _users_history

- name: "hardening | ensure ~{{ item.key }}/.bash_history is NOT in append only mode"
  file:
    path: "~{{ item.key }}/.bash_history"
    attr: -a
    state: touch
    owner: "{{ item.key }}"
    group: "{{ item.value.group | default(item.key) }}"
    mode: "0600"
  changed_when: false
  when:
    - _users_history.stat.exists
    - _users_status == "unset" or
      _users_status == "set_bash"

- name: "hardening | ensure ~{{ item.key }}/.bash_history is in append only mode so that content cannot be tampered with"
  file:
    path: "~{{ item.key }}/.bash_history"
    attr: a
    state: touch
    owner: "{{ item.key }}"
    group: "{{ item.value.group | default(item.key) }}"
    mode: "0600"
  changed_when: false
  when: _users_status == "set_bash"

- name: "hardening | ~{{ item.key }}/.profile"
  template:
    src: "{{ users_profile_template }}"
    dest: "~{{ item.key }}/.profile"
    owner: "root"
    group: "root"
    mode: 0644
  when:
    - (item.value.profile is defined and item.value.profile|length>0) or users_default_profile|length>0
    - _users_status == "set_profile"
