---
- name: "hardening | ensure {{ item.value.home }}/.bash_history exists"
  stat:
    path: "{{ item.value.home }}/.bash_history"
  register: history

- name: "hardening | ensure {{ item.value.home }}/.bash_history is NOT immutable"
  file:
    path: "{{ item.value.home }}/.bash_history"
    attr: -a
  changed_when: false
  when:
    - history.stat.exists
    - status == "unset"

- name: "hardening | ensure {{ item.value.home }}/.bash_history is immutable"
  file:
    path: "{{ item.value.home }}/.bash_history"
    attr: a
    state: touch
    owner: "{{ item.key }}"
    group: "{{ item.value.group | default(item.key) }}"
  changed_when: false
  when: status == "set_bash"

- name: "hardening | {{ item.value.home }}/.profile"
  template:
    src: "{{ user_profile_template }}"
    dest: "{{ item.value.home }}/.profile"
    owner: "root"
    group: "root"
    mode: 0644
  when:
    - "'profile' in item.value"
    - status == "set_profile"
