---
- name: Add OS specific variables
  include_vars: "{{ loop_vars }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
        - "{{ ansible_system | lower }}.yml"
      paths:
        - "vars"
      skip: true
  loop_control:
    loop_var: loop_vars

- name: "Update APT cache"
  apt:
    update_cache: true
  tags:
    - molecule-idempotence-notest
  when:
    - ansible_pkg_mgr == "apt"

# install packages
- include_tasks: install.yml

# create users and groups
- include_tasks: create_groups.yml
  loop: "{{ users | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
- include_tasks: create_users.yml
  loop: "{{ users | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

# configure user's profile
- include_tasks: configure_bash.yml
  loop: "{{ users | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
- include_tasks: configure_ssh.yml
  loop: "{{ users | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
- include_tasks: configure_vim.yml
  loop: "{{ users | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
- include_tasks: configure_profile.yml
  loop: "{{ users | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
