---
- name: "manage_groups | create group {{ item.value.group | default('') }}"
  ansible.builtin.group:
    name: "{{ item.value.group }}"
    gid: "{{ item.value.gid | default(omit) }}"
    state: "{{ item.value.state | default('present') }}"
  when: item.value.group is defined
