---
.default_image: &default_image
  privileged: true
  tty: true
  volumes:
    - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
  stop_signal: "SIGRTMIN+3"
  capabilities:
    - SYS_ADMIN
    - SYS_TIME
    - LINUX_IMMUTABLE

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - <<: *default_image
    name: claranet_users_centos-8
    image: centos:8
  - <<: *default_image
    name: claranet_users_debian-10
    image: debian:10
  - <<: *default_image
    name: claranet_users_amazon-latest
    image: amazonlinux:latest
provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "true"
  options:
    v: true
  playbooks:
    docker:
      cleanup: docker-cleanup.yml
verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    verbose: true
    s: true
lint: |
  ansible-lint
